# Generated by Django 6.0 on 2025-12-24 18:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado'), ('past_due', 'Pago Vencido')], default='pending', max_length=20, verbose_name='Estado')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Stripe Subscription ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección Completa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Renta Mensual')),
                ('billing_day', models.IntegerField(default=1, help_text='Día del mes para realizar el cobro (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de Cobro')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Stripe Customer ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('status', models.CharField(choices=[('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('pending', 'Pendiente'), ('refunded', 'Reembolsado')], max_length=20, verbose_name='Estado')),
                ('stripe_payment_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe Payment ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Razón de Fallo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.agreement', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='rentals.property', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='rentals.tenant', verbose_name='Inquilino'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('property',), name='unique_active_agreement_per_property'),
        ),
    ]
